apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest-deployment
  labels:
    app: devopstest
    tier: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstest
      tier: front-end
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devopstest
        tier: front-end
    spec:
      restartPolicy: Always
      containers:
      - name: devopstest-container
        image: techeduhub/devopstest:latest
        ports:
        - containerPort: 8081
