apiVersion: v1
kind: Service
metadata:
  name: devopstest-service
  labels:
    app: devopstest-service
    tier: front-end
spec:
  type: LoadBalancer
  ports:
    - port: 4040
      targetPort: 8080
      nodePort: 32000
  selector:
    app: devopstest
    tier: front-end
